name: dart_pcsc
description: Communicate with smart cards using PC/SC.
version: 1.1.0
repository: https://github.com/jjanku/dart_pcsc

platforms:
  linux:
  windows:

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  ffigen: ^5.0.0
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  async: ^2.8.2
  ffi: ^1.2.1
