name: dart_pcsc
description: Communicate with smart cards using PC/SC.
version: 2.0.1
repository: https://github.com/jjanku/dart_pcsc

platforms:
  linux:
  windows:
  macos:

environment:
  sdk: ^3.0.0

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^3.0.0
  test: ^1.16.0
dependencies:
  async: ^2.8.2
  ffi: ^2.0.2
