name: Dart

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Install test dependencies
        # TODO: replace with installation from the pkg manager
        # once vicc gets fixed
        run: |
          sudo apt-get install pcscd libpcsclite-dev help2man
          git clone https://github.com/frankmorgner/vsmartcard.git
          cd vsmartcard
          git submodule update --init --recursive
          cd virtualsmartcard
          autoreconf --verbose --install
          ./configure --sysconfdir=/etc
          make
          sudo make install
          sudo ln -s /usr/local/lib/python3.10/{site,dist}-packages/virtualsmartcard
          sudo systemctl restart pcscd

      - name: Setup test environment
        run: |
          vicc &

      - name: Run tests
        # TODO: test on Windows
        run: dart test -x interactive
